MODULE D02NVF_D02M_N
   USE, INTRINSIC :: ISO_C_BINDING

   INTEGER(C_INT) NEQF, LWORK, LIWORK, NRD, IFAILF, IT
   INTEGER(C_INT), PARAMETER :: NEQ = 6, NEQMAX = NEQ, NRW = 50 + 4*NEQMAX, NINF = 23, NWKJAC = NEQMAX*(NEQMAX + 1), &
                                MAXORD = 5, NY2DIM = MAXORD + 1, MAXSTP = 0, MXHNIL = 5
   REAL(C_DOUBLE), PARAMETER :: H0 = 0.0D0, HMAX = 10.0D0, HMIN = 1.0D-10
   INTEGER(C_INT) ITASK, ITOL, ITRACE, INFORM(NINF)
   REAL(C_DOUBLE) CONST(6), RWORK(NRW), WKJAC(NWKJAC), Y(NEQMAX), YDOT(NEQMAX), &
      YSAVE(NEQMAX, NY2DIM), TOUT, ATOL(NEQMAX), RTOL(NEQMAX), TCRIT, T, XOUT
   LOGICAL(C_BOOL), PARAMETER ::    PETZLD = .FALSE.

   REAL(C_DOUBLE), ALLOCATABLE, TARGET :: W_MONITR(:, :), WORK(:)

   COMMON XOUT, IT

   PRIVATE ALLOCATE_ARRAYS, DEALLOCATE_ARRAYS, NEQF

CONTAINS

   SUBROUTINE D02NVF_D02M_N_INIT(NE, NT, DT, TEND, FTOL, F)
      IMPLICIT NONE

      INTEGER(C_INT), INTENT(IN) :: NE, NT
      REAL(C_DOUBLE), INTENT(IN) :: TEND, FTOL, F(:), DT

      INTEGER(C_INT) I, IT
      REAL(C_DOUBLE) XOUT

      COMMON XOUT, IT

      NEQF = 6
      NRD = 6
      LWORK = 8*NEQF + 5*NRD + 21
      LIWORK = NRD + 21

      CALL ALLOCATE_ARRAYS(NT)
   END SUBROUTINE D02NVF_D02M_N_INIT

   SUBROUTINE ALLOCATE_ARRAYS(NT)
      IMPLICIT NONE

      INTEGER(C_INT) ERR_ALLOC, NT

      ALLOCATE (W_MONITR(3, NT), WORK(LWORK), STAT=ERR_ALLOC)

      IF (ERR_ALLOC /= 0) THEN
         PRINT *, "ALLOCATION ERROR"
         PAUSE
         STOP
      END IF
   END SUBROUTINE ALLOCATE_ARRAYS

   SUBROUTINE DEALLOCATE_ARRAYS()
      IMPLICIT NONE

      INTEGER(C_INT) ERR_DEALLOC

      DEALLOCATE (W_MONITR, WORK, STAT=ERR_DEALLOC)

      IF (ERR_DEALLOC /= 0) THEN
         PRINT *, "DEALLOCATION ERROR"
         PAUSE
         STOP
      END IF
   END SUBROUTINE DEALLOCATE_ARRAYS

END MODULE D02NVF_D02M_N
