MODULE DOPRF
   USE, INTRINSIC :: ISO_C_BINDING

   INTEGER(C_INT) NEQF, NRDF, LWORKF, LIWORKF, AIPARF(1), IPARF, IOUTF, IDIDF, ITOLF
   REAL(C_DOUBLE) RTOLF, ATOLF, RPARF, FTOL, ARTOLF(1), AATOLF(1), ARPARF(1)

   REAL(C_DOUBLE), ALLOCATABLE, TARGET :: WORKF(:), YF(:)
   INTEGER(C_INT), ALLOCATABLE, TARGET :: IWORKF(:)

   PRIVATE ALLOCATE_ARRAYS, DEALLOCATE_ARRAYS
CONTAINS
   SUBROUTINE DOPRF_INIT(NF, FTOLL)
      IMPLICIT NONE

      INTEGER(C_INT), INTENT(IN) :: NF
      REAL(C_DOUBLE), INTENT(IN) :: FTOLL

      NEQF = NF
      NRDF = NF
      LWORKF = 11*NEQF + 8*NRDF + 21
      LIWORKF = NRDF + 21

      FTOL = FTOLL

      CALL ALLOCATE_ARRAYS()
   END SUBROUTINE DOPRF_INIT

   SUBROUTINE ALLOCATE_ARRAYS()
      IMPLICIT NONE

      INTEGER(C_INT) ERR_ALLOC

      ALLOCATE (WORKF(LWORKF), IWORKF(LIWORKF), YF(NEQF), STAT=ERR_ALLOC)

      IF (ERR_ALLOC /= 0) THEN
         PRINT *, "ALLOCATION ERROR"
         PAUSE
         STOP
      END IF
   END SUBROUTINE ALLOCATE_ARRAYS

   SUBROUTINE DEALLOCATE_ARRAYS()
      USE, INTRINSIC :: ISO_C_BINDING
      IMPLICIT NONE

      INTEGER(C_INT) ERR_DEALLOC

      DEALLOCATE (WORKF, IWORKF, YF, STAT=ERR_DEALLOC)

      IF (ERR_DEALLOC /= 0) THEN
         PRINT *, "DEALLOCATION ERROR"
         PAUSE
         STOP
      END IF
   END SUBROUTINE DEALLOCATE_ARRAYS

END MODULE DOPRF
